
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "web-server"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.synced_folder "../desafio-vagrant", "/vagrant_data"
  config.vm.provision "shell", path: "provision.sh"
end
